pipeline {

  agent any



       environment {

       AWS_CREDENTIALS = credentials("AWS_credentials_id")

       }

       stages{

       stage("Checkout"){

       steps {
             
	     git branch: 'main', url: 'https://github.com/dhan1411/jenkins.git'

       }

       }

       stage("Terraform") {

       steps {

       dir('/var/lib/jenkins/workspace/Test1/Jenkins') {

        sh """ terraform init
	       terraform plan
	       terraform apply --auto-approve """

	       }
	       }
	       }
	       }
	       }
